system:

launch-pad:
  pad:
    enabled: true
    velocity-strength: 1

sound:
  commands:
    allowed: BLOCK_NOTE_BLOCK_PLING
    rejected: BLOCK_NOTE_BLOCK_BASS
    launch-pad: ENTITY_EGG_THROW

spawn:
  x:
  y:
  z:

punishments:
  ban:
    players:
    message:
    reason:

  mute:
    players:
    message:
    reason:

vanish:
  players-vanished:
  staff-see: true
  pickup-items: false

god:
  players:

freeze:
  players-freezed:

build:
  players-building:

mutechat:
  chat-muted: false
