system:

launch-pad:
  pad:
    enabled: true
    velocity-strength: 1

spawn:
  location:

punishments:
  ban:
    players:
    message:
    reason:

  mute:
    players:
    message:
    reason:

vanish-mode:
  players-vanished:
  pickup-items: false

god-mode:
  players:

freeze-mode:
  players:

build:
  players-building:

mute-chat:
  chat-muted: false

maintenance:
  state:

reports:
  players:

jail:
  location:
  players:

social-spies:
  spying-players:
  targeted-players:

server-motd:
  message:

pvp-mode:
  state:

name-tag:
  tag: