name: EssentialCommands
version: '${version}'
main: me.notro.essentialcommands.EssentialCommands
api-version: 1.19
authors: [ Notro ]
description: General commands in Minecraft

commands:

  heal:
    description: Set full health to a player.

  feed:
    description: Set full food level to a player.

  god:
    description: Set player to invincible.

  vanish:
    aliases: v
    description: Set player to invisible.

  clear:
    aliases: ci
    description: Clears Inventory.

  give:
    description: Give an item to a player.

  teleport:
    aliases: tp
    description: Teleports to a player.

  setSpawn:
    description: Set world spawn.

  spawn:
    description: Teleports to the spawn.

  fly:
    description: Set flight to a player.

  time:
    description: Set world time.

  freeze:
    description: Freeze/Unfreeze a player.

  gamemode:
    aliases: gm
    description: Set a certain game mode to a player.

  weather:
    description: Set server weather.

  kit:
    description: Set a kit for a player.

  push:
    description: Push a player to a certain distance.

  speed:
    description: Set a player flight speed.

  enchant:
    description: Set an enchantment to a certain item.

  staffchat:
    aliases: sc
    description: Send a message to the staff members only.

  build:
    description: Change build mode to a player.

  tpall:
    description: Teleports all players online.

  killall:
    description: Kill all the players.

  wear:
    aliases: equip, hat
    description: Wear a certain item.

  kick:
    description: Kick a player from the server.

  effect:
    description: Give a player certain effect.

  ban:
    aliases: b
    description: Ban a player.

  unban:
    description: Unban a player.

  ping:
    description: Display your ping.

  nuke:
    description: Nuke a player.

  mute:
    aliases: m
    description: Mute a player.

  unmute:
    description: Unmute a player.

  whitelist:
    description: Whitelist a player/server.

  mutechat:
    description: Mute the chat.

  msg:
    aliases: whisper
    description: Message a player.

  particle:
    description: Opens a particle GUI.

  summon:
    description: Summons an entity to a player.

  hologram:
    description: Display an awesome hologram by your choice.

  smite:
    description: Smite a player with a strong lightning.

  discord:
    description: Generates a link of a discord server.

  sign:
    aliases: i
    description: Gives a player a sign.

  tempban:
    aliases: tban
    description: Tempban a player for a certain duration.

  kill:
    description: Kill a player.

  tempmute:
    aliases: tmute
    description: Tempmute a player for a certain duration.

  broadcast:
    aliases: bc
    description: Broadcast a message to all the server.

  troll:
    description: Troll a player.

  rtp:
    aliases: jtp
    description: Randomly teleport to an online player.

  setwarp:
    description: Set a new warp from your current position.

  warp:
    description: Teleport to the named warp.

  unwarp:
    description: Removes a spcified warp.

  sudo:
    description: Send a message as an other player.

  invsee:
    description: Open's a target's inventory.

  firework:
    description: Send a firework to a player.

  shoot:
    description: Shoot a fireball at a player.

  staffhelp:
    aliases: sh
    description: Send a help message to an online staff.

  top:
    description: Sent a player to the top block in their current location.

  experience:
    description: Add a player experience levels.

  config:
    description: Reloads the default config.

  tphere:
    description: Tp a targeted player to sender.

  kickall:
    description: Kicks all players.

  maintenance:
    description: Sets maintenance mode.

  report:
    description: Report a player.

  reports:
    description: Show reports list.

  list:
    description: Represent a list of online players.

  setjail:
    description: Set a jail location.

  jail:
    description: Send a targeted player to the jail.

  rules:
    description: Display the current rules of the server, can also add/remove rules.

  giveall:
    description: Give a certain item to all players.

  socialmedia:
    description: Sends a social media information.

  socialspy:
    description: Social Spy on all players.

  playsound:
    aliases: ps
    description: Play a certain sound.

  motd:
    description: Set a cool MOTD.

  pvp:
    description: Toggle Server pvp.

  stafflist:
    description: Presents all the online staff.

  clearlag:
    description: Clears all entities.

  gravity:
    description: Set a player gravity to true/false.

  healall:
    description: Heal all online players.

  feedall:
    description: Feed all online players.

  trash:
    description: Open's a trash bin to clean items.

  head:
    aliases: skull
    description: Get a player's head.

  clearchat:
    aliases: cc
    description: Clears chat history.

  seen:
    description: Check when a player last played.

  save:
    description: Saves the specified world.

  oplist:
    description: Presents all the op players.

  difficulty:
    description: Set server difficulty.

  enderchest:
    aliases: echest
    description: Open a player's enderchest.

  speedall:
    description: Speed all online players.

  deletespawn:
    description: Delete the server current spawn point.

  send:
    description: Send a player to a specified world.

  fart:
    description: Makes a player fart.

  seed:
    description: Display world seed.

  stack:
    description: Set your current item amount to 64.

  smiteall:
    description: Smite all online players.

  explode:
    description: Explode a certain player.

  clearall:
    description: Clear all online players inventory.

  powertool:
    aliases: pt
    description: Set your held item an action.

  minefast:
    aliases: mf
    description: Set a player fast digging for a certain duration.

  fakejoin:
    aliases: fj
    description: Send a fake join message to troll all online players.

  find:
    description: Find a player.

  casino:
    description: Try your luck with getting cool stuff using casino.

  fakequit:
    description: Send a fake quit message to troll all online players.

  credits:
    description: Presents the plugin author & credit.